[project]
name = "dots"
version = "0.1.0"
description = "hello hello dots"
readme = "README.md"
requires-python = "==3.12"
dependencies = [
  "autorandr==1.14.post1",
  "pre-commit",
  "ruff",
  "virtualenvwrapper",
  "pip"
]
