[delta]
	navigate = true
	syntax-theme = gruvbox-dark

	commit-style = "#d5c4a1"
	file-style = "bold #d5c4a1"
	file-decoration-style = "#83a598 ul"
	hunk-header-style = "line-number syntax #3c3836"
	hunk-header-decoration-style = "#3c3836"
	hunk-header-line-number-style = "#fabd2f"

	plus-style = "syntax #32302f"
	plus-emph-style = "syntax bold #4a5f3b"
	plus-non-emph-style = "syntax #32302f"

	minus-style = "syntax #3f2323"
	minus-emph-style = "syntax bold #5f3b3b"
	minus-non-emph-style = "syntax #3f2323"

	line-numbers = true
	line-numbers-left-style = "#928374"
	line-numbers-right-style = "#928374"
	line-numbers-minus-style = "#fb4934 #3f2323"
	line-numbers-plus-style = "#b8bb26 #32302f"
	line-numbers-zero-style = "#928374"
