---
- name: Setup caps2esc
  hosts: home
  become: true
  connection: local

  tasks:
    - name: Add apt repository
      ansible.builtin.apt_repository:
        repo: 'ppa:deafmute/interception'
        state: present

    - name: Install packages
      apt:
        name: interception-caps2esc
        state: present

    - name: Add config for udevmon to a file
      copy:
        src: udevmon.yaml
        dest: /etc/udevmon.yaml
      notify: restart service

  handlers:
    - name: restart service
      systemd:
        name: udevmon
        state: restarted
